version: "3.8"

services:
  inventario:
    build:
      context: Microservicio-inventario
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-inventario:5432/ecommerce_inventario
      - SPRING_DATASOURCE_USERNAME=Solus
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=123456
    depends_on:
      - db-inventario
      - rabbitmq
    networks:
      - my_network

  venta:
    build:
      context: Microservicio-venta
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-venta:5432/ecommerce_venta     
      - SPRING_DATASOURCE_USERNAME=Solus  
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=123456
    depends_on:
      - db-venta
      - rabbitmq
    networks:
      - my_network

  pedido:
    build:
      context: Microservicio-pedido
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-pedido:5432/ecommerce_pedido     
      - SPRING_DATASOURCE_USERNAME=Solus  
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=123456
    depends_on:
      - db-pedido
      - rabbitmq
    networks:
      - my_network

  carrito:
    build:
      context: Microservicio-carrito
    ports:
      - "8084:8080"
    environment:    
      - SPRING_REDIS_HOST=redis-carrito  
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis-carrito
    networks:
      - my_network

  db-inventario:
    image: postgres:14
    environment:
      - POSTGRES_DB=ecommerce_inventario
      - POSTGRES_USER=Solus
      - POSTGRES_PASSWORD=123456
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-inventario:/var/lib/postgresql/data
    networks:
      - my_network

  db-venta:
    image: postgres:14
    environment:
      - POSTGRES_DB=ecommerce_venta
      - POSTGRES_USER=Solus
      - POSTGRES_PASSWORD=123456
    ports:
      - "5434:5432"
    volumes:
      - postgres-data-venta:/var/lib/postgresql/data
    networks:
      - my_network

  db-pedido:
    image: postgres:14
    environment:
      - POSTGRES_DB=ecommerce_pedido
      - POSTGRES_USER=Solus
      - POSTGRES_PASSWORD=123456
    ports:
      - "5435:5432"
    volumes:
      - postgres-data-pedido:/var/lib/postgresql/data
    networks:
      - my_network

  redis-carrito:
    image: redis:7.4
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    networks:
      - my_network
      
volumes:
  postgres-data-inventario:
  postgres-data-venta:
  postgres-data-pedido:
  redis-data:

networks:
  my_network:
    driver: bridge
